export const clients = [
  {
    id: "cli_01",
    name: "David Park",
    company: "Riviera Hospitality Group",
    email: "david.park@rivierahg.com",
    role: "VP of Marketing",
    status: "new-lead",
    lastContact: "2026-02-19T14:23:00Z",
    notes: "Inbound via website contact form. Needs full rebrand for boutique hotel chain.",
    estimatedValue: "$18,000",
  },
  {
    id: "cli_02",
    name: "Sarah Lin",
    company: "Nourish App",
    email: "sarah@nourishapp.io",
    role: "CEO & Founder",
    status: "active",
    lastContact: "2026-02-18T11:00:00Z",
    notes: "Ongoing product design retainer. Phase 2 UI refresh in progress.",
    estimatedValue: "$4,500/month",
  },
  {
    id: "cli_03",
    name: "Marcus Webb",
    company: "Archway Financial",
    email: "mwebb@archwayfinancial.com",
    role: "Director of Brand",
    status: "active",
    lastContact: "2026-02-17T16:45:00Z",
    notes: "Brand guidelines delivery due Friday. Final revisions pending.",
    estimatedValue: "$12,000",
  },
  {
    id: "cli_04",
    name: "Jessica Tran",
    company: "Bloom Collective",
    email: "jess@bloomcollective.co",
    role: "Creative Director",
    status: "follow-up-needed",
    lastContact: "2026-02-10T09:30:00Z",
    notes: "Proposal sent 9 days ago. No response. Past client — good relationship.",
    estimatedValue: "$7,500",
  },
];
