export const openclawTasks = [
  {
    id: "claw_task_01",
    name: "Write Daily Brief",
    type: "recurring",
    schedule: "every day at 8:00 AM local",
    cron: "0 8 * * *",
    status: "active",
    lastRun: "2026-02-20T08:00:00-08:00",
    nextRun: "2026-02-21T08:00:00-08:00",
    description: "Analyze inbox, calendar, invoices, and task list. Generate a natural-language morning brief for Maya.",
    outputs: ["dailyBrief"],
    dependencies: ["gmail", "googleCalendar", "clickup", "notion"],
  },
  {
    id: "claw_task_02",
    name: "Check Email",
    type: "recurring",
    schedule: "every hour, 9 AM – 6 PM local",
    cron: "0 9-18 * * *",
    status: "active",
    lastRun: "2026-02-20T09:00:00-08:00",
    nextRun: "2026-02-20T10:00:00-08:00",
    description: "Scan inbox for new messages. Triage by urgency. Draft replies for high-priority items. Flag anything requiring Maya's attention.",
    outputs: ["emailTriage", "draftReplies", "notifications"],
    dependencies: ["gmail"],
    rules: [
      "Skip newsletters and marketing emails — archive automatically",
      "Flag anything from an active or past client as medium+ priority",
      "New inbound leads from unknown senders get high priority",
      "Draft replies match Maya's professional-warm voice",
      "Never send a reply without approval unless trust level is set to auto",
    ],
  },
  {
    id: "claw_task_03",
    name: "Check Pending Invoices",
    type: "recurring",
    schedule: "every day at 9:00 AM local",
    cron: "0 9 * * *",
    status: "active",
    lastRun: "2026-02-20T09:00:00-08:00",
    nextRun: "2026-02-21T09:00:00-08:00",
    description: "Review all outstanding invoices. Flag overdue items. Send gentle payment reminders for invoices 3+ days past due.",
    outputs: ["invoiceReport", "paymentReminders"],
    dependencies: ["stripe", "gmail"],
    rules: [
      "First reminder: friendly nudge at 3 days overdue",
      "Second reminder: firmer tone at 7 days overdue",
      "Escalation flag at 14 days — suggest Maya call directly",
      "Log all payment activity to daily brief",
    ],
  },
  {
    id: "claw_task_04",
    name: "Check Task List",
    type: "recurring",
    schedule: "every day at 8:30 AM local",
    cron: "30 8 * * *",
    status: "active",
    lastRun: "2026-02-20T08:30:00-08:00",
    nextRun: "2026-02-21T08:30:00-08:00",
    description: "Review ClickUp and Notion for overdue tasks, upcoming deadlines, and blocked items. Surface in daily brief and send notifications for anything due today.",
    outputs: ["taskSummary", "notifications"],
    dependencies: ["clickup", "notion"],
    rules: [
      "Tasks due today get surfaced with time estimates",
      "Overdue tasks get flagged with suggested reschedule options",
      "Blocked tasks get escalated with context on the blocker",
    ],
  },
  {
    id: "claw_task_05",
    name: "Situate a Client",
    type: "on-demand",
    schedule: "triggered when a new client interaction occurs",
    cron: null,
    status: "active",
    lastRun: "2026-02-19T15:15:00-08:00",
    nextRun: null,
    description: "When a new client or lead appears, create a full context package: Notion page with discovery notes, ClickUp project with initial tasks, calendar prep block, and background research.",
    outputs: ["notionPage", "clickupProject", "calendarPrepBlock", "clientProfile"],
    dependencies: ["gmail", "googleCalendar", "clickup", "notion"],
    trigger: {
      event: "new-client-email-detected",
      lastTriggeredBy: "email_01",
      lastTriggeredAt: "2026-02-19T14:23:00Z",
    },
    rules: [
      "Create Notion discovery page with company overview and prep questions",
      "Create ClickUp project with initial milestones",
      "Block 15 min before the first call for prep",
      "Research client's company, LinkedIn, and recent news",
      "Estimate project value based on scope signals in the email",
    ],
  },
];

export const openclawActivityLog = [
  {
    id: "log_01",
    timestamp: "2026-02-19T14:23:30Z",
    task: "claw_task_02",
    action: "email-triaged",
    detail: "New email from David Park (Riviera HG) — classified as high-priority new lead.",
  },
  {
    id: "log_02",
    timestamp: "2026-02-19T14:25:00Z",
    task: "claw_task_02",
    action: "reply-drafted",
    detail: "Drafted response with 3 calendar slots for David Park.",
  },
  {
    id: "log_03",
    timestamp: "2026-02-19T14:28:00Z",
    task: "claw_task_02",
    action: "reply-sent",
    detail: "Auto-sent reply to David Park (trust level: auto for calendar-slot responses).",
  },
  {
    id: "log_04",
    timestamp: "2026-02-19T15:10:30Z",
    task: "claw_task_02",
    action: "email-triaged",
    detail: "David Park confirmed Thursday 1 PM slot.",
  },
  {
    id: "log_05",
    timestamp: "2026-02-19T15:12:00Z",
    task: "claw_task_05",
    action: "calendar-invite-created",
    detail: "Created Google Calendar invite: 'Intro Call — Maya Chen × David Park' for Thu Feb 20, 1 PM PST.",
  },
  {
    id: "log_06",
    timestamp: "2026-02-19T15:15:00Z",
    task: "claw_task_05",
    action: "task-created",
    detail: "Created ClickUp task: 'Prep for Riviera Rebrand intro call' — due Thu 12:45 PM.",
  },
  {
    id: "log_07",
    timestamp: "2026-02-19T15:20:00Z",
    task: "claw_task_05",
    action: "notion-page-created",
    detail: "Created Notion page: 'Riviera Hospitality — Rebrand Discovery' with research, questions, and competitor refs.",
  },
  {
    id: "log_08",
    timestamp: "2026-02-20T08:00:00Z",
    task: "claw_task_01",
    action: "daily-brief-generated",
    detail: "Morning brief generated for Thursday Feb 20. 5 schedule items, 3 emails flagged, 1 overdue invoice, 1 follow-up needed.",
  },
  {
    id: "log_09",
    timestamp: "2026-02-20T08:30:00Z",
    task: "claw_task_04",
    action: "task-list-checked",
    detail: "4 tasks due today/tomorrow. All surfaced in daily brief. No blocked items.",
  },
  {
    id: "log_10",
    timestamp: "2026-02-20T09:00:00Z",
    task: "claw_task_03",
    action: "invoices-checked",
    detail: "1 outstanding invoice: Archway Financial $6,000 (due Feb 25). Not yet overdue — reminder queued for Feb 22 if unpaid.",
  },
];
