export const tasks = [
  {
    id: "task_01",
    title: "Prep for Riviera Rebrand intro call",
    description: "Review David Park's LinkedIn profile and Riviera Hospitality Group website. Prepare 3–5 discovery questions about brand positioning goals.",
    status: "todo",
    priority: "high",
    dueDate: "2026-02-20T12:45:00-08:00",
    project: "Riviera Hospitality — Rebrand",
    assignee: "Maya Chen",
    createdBy: "openclaw",
    createdAt: "2026-02-19T15:15:00Z",
    source: "clickup",
    linkedEmail: "email_01",
    linkedCalendarEvent: "evt_03",
    tags: ["new-lead", "call-prep"],
  },
  {
    id: "task_02",
    title: "Update recipe detail page background — Nourish Phase 2",
    description: "Sarah requested a warmer background on the recipe detail page. Try warm linen tone. Send revision by EOD Feb 20.",
    status: "todo",
    priority: "medium",
    dueDate: "2026-02-20T17:00:00-08:00",
    project: "Nourish App — Phase 2",
    assignee: "Maya Chen",
    createdBy: "openclaw",
    createdAt: "2026-02-19T11:15:00Z",
    source: "clickup",
    linkedEmail: "email_04",
    tags: ["revision", "design"],
  },
  {
    id: "task_03",
    title: "Archway brand guidelines — add social avatar section + brighter palette",
    description: "Marcus requested two changes: (1) Add a section on social media avatar usage, (2) Explore a brighter secondary color palette. Due Friday Feb 21.",
    status: "todo",
    priority: "high",
    dueDate: "2026-02-21T17:00:00-08:00",
    project: "Archway Financial — Brand Guidelines",
    assignee: "Maya Chen",
    createdBy: "openclaw",
    createdAt: "2026-02-18T17:00:00Z",
    source: "clickup",
    linkedEmail: "email_06",
    tags: ["revision", "brand", "deadline-friday"],
  },
  {
    id: "task_04",
    title: "Send follow-up to Jessica Tran — Bloom Collective proposal",
    description: "Proposal sent 9 days ago with no response. Send warm follow-up email. Draft ready for review in email queue.",
    status: "todo",
    priority: "medium",
    dueDate: "2026-02-20T12:00:00-08:00",
    project: "Bloom Collective — Pitch",
    assignee: "Maya Chen",
    createdBy: "openclaw",
    createdAt: "2026-02-20T08:00:00Z",
    source: "notion",
    linkedClient: "cli_04",
    tags: ["follow-up", "proposal"],
  },
];

export const notionPage = {
  id: "notion_page_01",
  title: "Riviera Hospitality — Rebrand Discovery",
  workspace: "Maya Chen Design",
  createdBy: "openclaw",
  createdAt: "2026-02-19T15:20:00Z",
  content: {
    overview: "New lead from David Park, VP Marketing at Riviera Hospitality Group. 4 boutique hotels on the California coast. Full rebrand scope: logo, visual identity, website, collateral.",
    callNotes: "Intro call scheduled: Thu Feb 20, 1:00 PM PST",
    discoveryQuestions: [
      "What's driving the rebrand now? New ownership, repositioning, or refresh?",
      "Who is the target guest persona — luxury leisure, business, or mixed?",
      "Are there any brand elements you want to keep vs. start fresh?",
      "What does success look like 6 months after launch?",
      "Timeline and budget range for the full project?",
    ],
    competitorReferences: [
      { name: "Ace Hotel", url: "https://acehotel.com", note: "Modern boutique positioning" },
      { name: "1 Hotel", url: "https://1hotels.com", note: "Nature-forward luxury" },
      { name: "The LINE", url: "https://thelinehotel.com", note: "Culture + design-led" },
    ],
    estimatedValue: "$18,000",
    nextStep: "Complete intro call → send proposal within 48 hours",
  },
};
