import React, { useState, useRef, useEffect } from 'react';
import './Scenario.css';
import {
  Mail, Send, Calendar, CheckCircle2, Clock, ChevronRight,
  FileText, Users, Sparkles, ArrowRight, Bot, ClipboardList,
  Sun, MailCheck, Receipt, ListChecks, UserPlus, Plus, Play
} from 'lucide-react';

import db, { freelancer } from '../../mock-data/index';
import { scenarioOnlyEmails } from '../../mock-data/seed';
import eventBus from '../../mock-data/eventBus';
import { calendarSlots, calendarInvite } from '../../mock-data/scenario/calendar';
import { notionPage } from '../../mock-data/scenario/tasks';
import { openclawTasks } from '../../mock-data/scenario/openclawTasks';

const clients = db.collection('clients').getAll();
const dailyBrief = db.collection('dailyBriefs').getAll()[0];
const tasks = db.collection('tasks').getAll();

const DASHBOARD_URL = '/dashboard?chiefclaw=true';

const SCENARIO_CHAT_MESSAGES = [
  'New email received from David Park — rebrand inquiry for Riviera Hospitality Group. Triaging now...',
  "I've drafted a response with 3 calendar slots and sent it to David on your behalf.",
  'David confirmed Thursday at 1 PM PST. Processing the confirmation...',
  'Calendar invite created — Intro Call with David Park, Thursday 1 PM via Google Meet.',
  'Prep tasks created in ClickUp. Discovery page set up in Notion.',
  'Good morning, Maya. Here is your daily brief for today.',
];

const SCENARIO_VIEW_MAP = [
  'inbox',
  'drafting',
  'inbox',
  'schedule',
  'todos',
  'empty',
];

const SCENARIO_SEQUENCE = [
  { emailId: 'email_01', delay: 0, logMessage: 'David Park sends an email requesting a call about a rebrand project.' },
  { emailId: 'email_02', delay: 2000, logMessage: 'OpenClaw triages the email, drafts a response with 3 calendar slots, and sends it.' },
  { emailId: 'email_03', delay: 2500, logMessage: 'David confirms Thursday at 1 PM PST.' },
  { event: 'calendar', delay: 1500, logMessage: 'OpenClaw creates a Google Calendar invite with agenda and Meet link.' },
  { event: 'tasks', delay: 1500, logMessage: 'OpenClaw creates prep tasks in ClickUp and a discovery page in Notion.' },
  { event: 'brief', delay: 2000, logMessage: 'Next morning — OpenClaw generates the daily brief.' },
];

const CLAW_TASKS_LIST = [
  { task: openclawTasks[0], icon: Sun, color: '#e83e8c' },
  { task: openclawTasks[1], icon: MailCheck, color: '#007bff' },
  { task: openclawTasks[2], icon: Receipt, color: '#fd7e14' },
  { task: openclawTasks[3], icon: ListChecks, color: '#20c997' },
  { task: openclawTasks[4], icon: UserPlus, color: '#6f42c1' },
];

function formatTime(iso) {
  return new Date(iso).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
}

function formatDate(iso) {
  return new Date(iso).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
}

function EmailCard({ email, isNew }) {
  const [expanded, setExpanded] = useState(false);
  const isOutbound = email.direction === 'outbound';
  return (
    <div
      className={`email-card ${isOutbound ? 'outbound' : 'inbound'} ${expanded ? 'expanded' : ''} ${isNew ? 'email-new' : ''}`}
      onClick={() => setExpanded(!expanded)}
    >
      <div className="email-card-header">
        <div className="email-card-direction">
          {isOutbound ? <Send size={14} /> : <Mail size={14} />}
          <span>{isOutbound ? 'Sent' : 'Received'}</span>
        </div>
        <span className="email-card-time">{formatTime(email.timestamp || email.receivedAt || email.sentAt)}</span>
      </div>
      <div className="email-card-from">
        {isOutbound ? `To: ${email.to.name}` : `From: ${email.from.name}`}
      </div>
      <div className="email-card-subject">{email.subject}</div>
      {email.clawSummary && (
        <div className="claw-summary">
          <Sparkles size={12} />
          <span>{email.clawSummary}</span>
        </div>
      )}
      {expanded && (
        <div className="email-card-body">
          <pre>{email.body}</pre>
        </div>
      )}
      {email.generatedBy === 'openclaw' && (
        <div className="generated-badge">
          <Bot size={12} /> Generated by OpenClaw
        </div>
      )}
    </div>
  );
}

function CalendarInviteCard() {
  return (
    <div className="invite-card email-new">
      <div className="invite-header">
        <Calendar size={20} />
        <span>Calendar Invite Created</span>
        <span className="invite-badge confirmed">Confirmed</span>
      </div>
      <h3 className="invite-title">{calendarInvite.title}</h3>
      <div className="invite-details">
        <div className="invite-detail-row">
          <Clock size={14} />
          <span>{formatDate(calendarInvite.datetime)} at {formatTime(calendarInvite.datetime)} — {calendarInvite.duration} min</span>
        </div>
        <div className="invite-detail-row">
          <Users size={14} />
          <span>{calendarInvite.attendees.map(a => a.name).join(' & ')}</span>
        </div>
      </div>
      <div className="invite-slots">
        <div className="slots-label">Slots Offered:</div>
        {calendarSlots.offered.map(slot => (
          <div key={slot.id} className={`slot-chip ${slot.status === 'selected' ? 'selected' : ''}`}>
            {slot.label}
            {slot.status === 'selected' && <CheckCircle2 size={14} />}
          </div>
        ))}
      </div>
      <div className="invite-description">
        <pre>{calendarInvite.description}</pre>
      </div>
    </div>
  );
}

function DailyBriefCard() {
  const [expandedSection, setExpandedSection] = useState(null);
  const iconMap = { calendar: Calendar, mail: Mail, 'dollar-sign': Receipt, 'user-check': Users };

  return (
    <div className="brief-card email-new">
      <div className="brief-greeting">{dailyBrief.greeting}</div>
      <div className="brief-stats">
        <div className="stat-chip"><Mail size={14} /> <strong>{dailyBrief.stats.pendingEmails}</strong> emails</div>
        <div className="stat-chip"><Receipt size={14} /> <strong>${dailyBrief.stats.revenueThisMonth.toLocaleString()}</strong> revenue</div>
        <div className="stat-chip"><Users size={14} /> <strong>{dailyBrief.stats.activeClients}</strong> clients</div>
        <div className="stat-chip"><ListChecks size={14} /> <strong>{dailyBrief.stats.tasksDueToday}</strong> tasks</div>
      </div>
      <div className="brief-summary">{dailyBrief.summary}</div>

      <div className="brief-sections">
        {dailyBrief.sections.map((section, idx) => {
          const Icon = iconMap[section.icon] || FileText;
          const isOpen = expandedSection === idx;
          return (
            <div key={idx} className={`brief-section ${isOpen ? 'open' : ''}`}>
              <button className="brief-section-header" onClick={() => setExpandedSection(isOpen ? null : idx)}>
                <Icon size={16} />
                <span>{section.title}</span>
                <span className="section-count">{section.items.length}</span>
                <ChevronRight size={16} className={`chevron ${isOpen ? 'rotated' : ''}`} />
              </button>
              {isOpen && (
                <div className="brief-section-body">
                  {section.items.map((item, i) => (
                    <div key={i} className={`brief-item ${item.status || ''} ${item.highlight ? 'highlight' : ''}`}>
                      {item.time && <span className="brief-item-time">{item.time}</span>}
                      <span className="brief-item-label">{item.label}</span>
                      {item.detail && <span className="brief-item-detail">{item.detail}</span>}
                      {item.suggestedAction && <span className="brief-item-action">{item.suggestedAction}</span>}
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {dailyBrief.clawNotes.length > 0 && (
        <div className="claw-notes">
          <div className="claw-notes-header"><Sparkles size={14} /> Claw's Notes</div>
          {dailyBrief.clawNotes.map((note, i) => (
            <div key={i} className="claw-note">{note}</div>
          ))}
        </div>
      )}
    </div>
  );
}

function TasksPanel() {
  return (
    <div className="tasks-card email-new">
      <div className="tasks-section">
        <h4><ClipboardList size={16} /> Tasks Auto-Created</h4>
        {tasks.slice(0, 2).map(task => (
          <div key={task.id} className={`task-item priority-${task.priority}`}>
            <div className="task-item-header">
              <span className={`priority-dot ${task.priority}`}></span>
              <span className="task-title">{task.title}</span>
            </div>
            <div className="task-meta">
              <span className="task-source">{task.source}</span>
              <span className="task-due">Due: {formatDate(task.dueDate)} {formatTime(task.dueDate)}</span>
            </div>
            <div className="task-description">{task.description}</div>
          </div>
        ))}
      </div>
      <div className="tasks-section notion-section">
        <h4><FileText size={16} /> Notion Discovery Page</h4>
        <div className="notion-card">
          <div className="notion-title">{notionPage.title}</div>
          <p className="notion-overview">{notionPage.content.overview}</p>
          <div className="notion-subsection">
            <strong>Discovery Questions</strong>
            <ul>
              {notionPage.content.discoveryQuestions.map((q, i) => <li key={i}>{q}</li>)}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

function Scenario() {
  const [feedItems, setFeedItems] = useState([]);
  const [currentStep, setCurrentStep] = useState(-1);
  const [isRunning, setIsRunning] = useState(false);
  const [activityLog, setActivityLog] = useState([]);
  const feedEndRef = useRef(null);
  const timeoutsRef = useRef([]);
  const dashboardTabRef = useRef(null);

  const ensureDashboardTab = () => {
    if (!dashboardTabRef.current || dashboardTabRef.current.closed) {
      dashboardTabRef.current = window.open(DASHBOARD_URL, 'openclaw-dashboard');
    } else {
      dashboardTabRef.current.focus();
    }
  };

  const david = clients.find(c => c.id === 'cli_01');

  useEffect(() => {
    feedEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [feedItems]);

  const clearTimeouts = () => {
    timeoutsRef.current.forEach(t => clearTimeout(t));
    timeoutsRef.current = [];
  };

  const dispatchToDashboard = (stepIdx, email) => {
    if (email) {
      eventBus.emit('inbox:add', { email: { ...email } });
    }

    eventBus.emit('chat:typing', { isTyping: true });

    const t1 = setTimeout(() => {
      eventBus.emit('chat:typing', { isTyping: false });
      eventBus.emit('chat:message', {
        text: SCENARIO_CHAT_MESSAGES[stepIdx],
        role: 'system',
      });
    }, 800);
    timeoutsRef.current.push(t1);

    const t2 = setTimeout(() => {
      eventBus.emit('ui:switchView', {
        workspace: SCENARIO_VIEW_MAP[stepIdx],
      });
      if (email && email.direction === 'inbound') {
        eventBus.emit('ui:selectEmail', { emailId: email.id });
      }
    }, 1200);
    timeoutsRef.current.push(t2);
  };

  const simulateNextStep = (stepIdx) => {
    if (stepIdx >= SCENARIO_SEQUENCE.length) {
      setIsRunning(false);
      return;
    }

    const step = SCENARIO_SEQUENCE[stepIdx];
    setCurrentStep(stepIdx);

    const logEntry = {
      id: `sim_${stepIdx}`,
      timestamp: new Date().toISOString(),
      detail: step.logMessage,
    };

    if (step.emailId) {
      const email = scenarioOnlyEmails.find(e => e.id === step.emailId);
      if (email) {
        setFeedItems(prev => [...prev, { type: 'email', data: email, key: step.emailId }]);
        dispatchToDashboard(stepIdx, email);
      }
    } else if (step.event === 'calendar') {
      setFeedItems(prev => [...prev, { type: 'calendar', key: 'calendar' }]);
      dispatchToDashboard(stepIdx, null);
    } else if (step.event === 'tasks') {
      setFeedItems(prev => [...prev, { type: 'tasks', key: 'tasks' }]);
      dispatchToDashboard(stepIdx, null);
    } else if (step.event === 'brief') {
      setFeedItems(prev => [...prev, { type: 'brief', key: 'brief' }]);
      dispatchToDashboard(stepIdx, null);
    }

    setActivityLog(prev => [logEntry, ...prev]);

    const nextDelay = stepIdx + 1 < SCENARIO_SEQUENCE.length ? SCENARIO_SEQUENCE[stepIdx + 1].delay : 0;
    if (nextDelay > 0 && stepIdx + 1 < SCENARIO_SEQUENCE.length) {
      const t = setTimeout(() => simulateNextStep(stepIdx + 1), nextDelay);
      timeoutsRef.current.push(t);
    }
  };

  const handleSimulateEmail = () => {
    if (isRunning) return;

    if (currentStep >= SCENARIO_SEQUENCE.length - 1) {
      clearTimeouts();
      setFeedItems([]);
      setActivityLog([]);
      setCurrentStep(-1);
      eventBus.emit('scenario:reset', {});
    }

    ensureDashboardTab();
    setIsRunning(true);
    simulateNextStep(currentStep + 1);
  };

  const handleRunAll = () => {
    clearTimeouts();
    setFeedItems([]);
    setActivityLog([]);
    setCurrentStep(-1);
    setIsRunning(true);
    eventBus.emit('scenario:reset', {});
    ensureDashboardTab();

    let cumDelay = 0;
    SCENARIO_SEQUENCE.forEach((step, idx) => {
      cumDelay += step.delay;
      const t = setTimeout(() => {
        simulateNextStep(idx);
        if (idx === SCENARIO_SEQUENCE.length - 1) {
          setIsRunning(false);
        }
      }, cumDelay);
      timeoutsRef.current.push(t);
    });
  };

  const handleReset = () => {
    clearTimeouts();
    setFeedItems([]);
    setActivityLog([]);
    setCurrentStep(-1);
    setIsRunning(false);
    eventBus.emit('scenario:reset', {});
  };

  const nextStepLabel = currentStep < 0
    ? 'David sends an email'
    : currentStep + 1 < SCENARIO_SEQUENCE.length
      ? SCENARIO_SEQUENCE[currentStep + 1].logMessage
      : null;

  const isComplete = currentStep >= SCENARIO_SEQUENCE.length - 1 && !isRunning;

  return (
    <div className="scenario-page">
      <div className="scenario-header">
        <div className="scenario-header-left">
          <div className="scenario-kicker">Demo Scenario</div>
          <h1>A Day with OpenClaw</h1>
          <p className="scenario-subtitle">
            Simulate how OpenClaw handles a new client lead — step by step.
          </p>
        </div>
        <div className="scenario-persona">
          <div className="persona-avatar">{freelancer.name.charAt(0)}</div>
          <div>
            <div className="persona-name">{freelancer.name}</div>
            <div className="persona-role">{freelancer.businessType}</div>
          </div>
        </div>
      </div>

      <div className="scenario-layout">
        {/* Sidebar */}
        <aside className="step-nav">
          <div className="step-nav-label">Controls</div>

          <button
            className={`sim-btn sim-btn-primary ${isRunning ? 'disabled' : ''}`}
            onClick={handleSimulateEmail}
            disabled={isRunning}
          >
            {isComplete ? (
              <><Play size={16} /> Restart Scenario</>
            ) : (
              <><Plus size={16} /> {currentStep < 0 ? 'Simulate Client Email' : 'Next Step'}</>
            )}
          </button>

          {currentStep < 0 && (
            <button className="sim-btn sim-btn-outline" onClick={handleRunAll} disabled={isRunning}>
              <Play size={16} /> Run Full Demo
            </button>
          )}

          {(currentStep >= 0 || feedItems.length > 0) && (
            <button className="sim-btn sim-btn-ghost" onClick={handleReset}>
              Reset
            </button>
          )}

          {nextStepLabel && !isRunning && (
            <div className="next-hint">
              <ArrowRight size={12} />
              <span>Next: {nextStepLabel}</span>
            </div>
          )}

          {isRunning && (
            <div className="running-indicator">
              <span className="running-dot"></span>
              Processing...
            </div>
          )}

          <div className="step-nav-divider"></div>
          <div className="step-nav-label">Progress</div>
          {SCENARIO_SEQUENCE.map((step, idx) => {
            const done = idx <= currentStep;
            const active = idx === currentStep && isRunning;
            return (
              <div key={idx} className={`progress-step ${done ? 'done' : ''} ${active ? 'active' : ''}`}>
                <span className="progress-dot">{done ? <CheckCircle2 size={14} /> : <span className="progress-num">{idx + 1}</span>}</span>
                <span className="progress-label">{step.logMessage.split('—')[0].split('.')[0]}</span>
              </div>
            );
          })}

          <div className="step-nav-divider"></div>
          <div className="step-nav-label">OpenClaw Tasks</div>
          {CLAW_TASKS_LIST.map(({ task, icon: Icon, color }) => (
            <div key={task.id} className="claw-task-item">
              <span className="claw-task-icon" style={{ background: `${color}15`, color }}><Icon size={14} /></span>
              <div className="claw-task-info">
                <span className="claw-task-name">{task.name}</span>
                <span className="claw-task-schedule">{task.schedule}</span>
              </div>
            </div>
          ))}
        </aside>

        {/* Main Feed */}
        <main className="step-content">
          {feedItems.length === 0 && (
            <div className="empty-feed">
              <div className="empty-feed-icon"><Mail size={40} /></div>
              <h3>No emails yet</h3>
              <p>Click "Simulate Client Email" to start the demo. David Park will send an email requesting a call about a rebrand project.</p>
            </div>
          )}

          <div className="feed-list">
            {feedItems.map((item) => {
              if (item.type === 'email') {
                return <EmailCard key={item.key} email={item.data} isNew />;
              }
              if (item.type === 'calendar') {
                return <CalendarInviteCard key={item.key} />;
              }
              if (item.type === 'tasks') {
                return <TasksPanel key={item.key} />;
              }
              if (item.type === 'brief') {
                return <DailyBriefCard key={item.key} />;
              }
              return null;
            })}
            <div ref={feedEndRef} />
          </div>

          {activityLog.length > 0 && (
            <div className="activity-timeline">
              <h4>Activity Log</h4>
              <div className="timeline-entries">
                {activityLog.map(entry => (
                  <div key={entry.id} className="timeline-entry">
                    <div className="timeline-dot"></div>
                    <div className="timeline-content">
                      <span className="timeline-time">{new Date(entry.timestamp).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', second: '2-digit', hour12: true })}</span>
                      <span className="timeline-detail">{entry.detail}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </main>
      </div>
    </div>
  );
}

export default Scenario;
